services:
  nginx:
    image: nginx:1.28-alpine
    container_name: bcms_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - bcms_net

  postgres:
    image: postgres:18-alpine
    container_name: bcms_postgres
    environment:
      POSTGRES_DB: bcms
      POSTGRES_USER: bcms
      POSTGRES_PASSWORD: bcms_password
    ports:
      - "54328:5432"
    volumes:
      - bcms_pgdata:/var/lib/postgresql/data
    networks:
      - bcms_net

  redis:
    image: redis:8-alpine
    container_name: bcms_redis
    ports:
      - "63798:6379"
    networks:
      - bcms_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bcms_backend
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - bcms_net

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bcms_scheduler
    working_dir: /var/www/html
    command: ["sh", "-lc", "php -v && while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"]
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - backend
      - postgres
      - redis
    networks:
      - bcms_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bcms_frontend
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - ./frontend:/app
    networks:
      - bcms_net

  adminer:
    image: adminer:4
    container_name: bcms_adminer
    ports:
      - "8081:8080"
    networks:
      - bcms_net

volumes:
  bcms_pgdata:

networks:
  bcms_net:
    driver: bridge